TARGET_LANGUAGES = [
    "AFRIKAANS",
    "SWAHILI",
    "YORUBA",
    "IGBO",
    "HAUSA",
    "ZULU",
    "SOMALI`",
    "NIGERIAN PIDGIN",
    "ARABIC"
]


TARGET_DOMAINS = [
    "TRANSLATION",
    "MATHEMATICS",
    "INFORMATION_SEEKING",
    "REASONING",
    "PLANNING",
    "ROLEPLAYING",
    "CREATIVE_WRITING",
    "STORYTELLING",
    "ADVICE_SEEKING",
]

SUBDOMAINS = [
    "Local and traditional foods and recipes",
    "Music (traditional and contemporary African genres)",
    "Sports (especially football/soccer)",
    "Business and entrepreneurship opportunities",
    "Agriculture and farming",
    "Education and skills development",
    "Family and relationships",
    "Local languages and cultures",
    "Mobile money and fintech",
    "Healthcare and wellness",
    "Fashion and style",
    "Entertainment (movies, TV shows)",
    "Religion and spirituality",
    "Community support systems",
    "Technology and innovation",
    "Market prices and trading",
    "Weather patterns and seasons",
    "Transportation and logistics",
    "Housing and real estate",
    "Youth empowerment",
    "Cultural celebrations and festivals",
    "Personal finance management",
    "Career development",
    "Current local events",
    "Politics and governance",
    "Wildlife and conservation",
    "Rural development",
    "Solar energy and power solutions",
    "Diaspora connections",
    "Small-scale mining",
    "Beauty and cosmetics",
    "Urban lifestyle",
    "Marriage customs",
    "Child-rearing practices",
    "Digital skills",
    "Scholarships and studying abroad",
    "Import/Export business",
    "Folk stories and proverbs",
    "Dance and performance arts",
    "Climate change adaptation",
    "Water access and management",
    "Livestock keeping",
    "Cross-border trade",
    "Historical figures and events",
    "Mental health and wellbeing",
    "Civic education",
    "Professional networking",
    "Gender equality",
    "Land ownership",
    "Waste management solutions",
    "Photography and art",
    "Sports betting",
    "Tourism opportunities",
    "Gaming and esports",
    "Crafts and artisanal skills",
    "Sustainable living",
    "Construction and building",
    "Vehicle maintenance",
    "Social media trends",
    "Food preservation",
    "Digital payments",
    "Environmental conservation",
    "Public transportation hacks",
    "Street food culture",
    "Home maintenance",
    "Job hunting strategies",
    "Tech startups",
    "Security awareness",
    "Natural hair care",
    "Community organizing",
    "Outdoor activities",
   " Market analysis",
   " Legal rights awareness",
]